version: "3.11"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: 723854145424.dkr.ecr.us-west-1.amazonaws.com/litellm-repo:test
  # image: ghcr.io/berriai/litellm:main-stable

    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
      # - MAX_DISK_SPACE=${MAX_DISK_SPACE}
      # - PUBLIC_NAME=${PUBLIC_NAME}
      # - MODEL=${MODEL}
      # - INITIAL_PEERS=${INITIAL_PEERS}
      # - DEVICE=${DEVICE}
      # - BLOCKS=${BLOCKS}
      # - PORT=${PORT}
    ##
        DATABASE_URL: "postgresql://postgres:example@db:5432/postgres"
        STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
    env_file:
      - .env # Load local .env file
    volumes:
      - ./proxy_server_config.yaml:/app/proxy_server_config.yaml
      - ./litellm:/app/litellm

    command: [ "--config", "/app/proxy_server_config.yaml" ]
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready"]
    #  interval: 1s
    #  timeout: 5s
    #  retries: 10

# ...rest of your docker-compose config if any

