model_list:
  - model_name: petals-llama-3
    litellm_params:
      model: "petals/meta-llama/Meta-Llama-3-70B"
    optional_params:
      initial_peers: ""     
  - model_name: petals-sauerkraut
    litellm_params:
      model: "petals/VAGOsolutions/SauerkrautLM-Mixtral-8x7B-Instruct"
    optional_params:
      initial_peers: ""
    model_info:
      id: "1"

router_settings:
  routing_strategy: usage-based-routing-v2 
  enable_pre_call_checks: true

general_settings: 
  master_key: sk-1234 # [OPTIONAL] Use to enforce auth on proxy. See - https://docs.litellm.ai/docs/proxy/virtual_keys
  store_model_in_db: True
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 1
  database_connection_pool_limit: 10

